# Cliente C1 - Ubuntu 18.04 LTS
FROM ubuntu:18.04

# Instalar cliente SSH y herramientas de red
RUN apt-get update && \
    apt-get install -y openssh-client tcpdump net-tools iputils-ping && \
    rm -rf /var/lib/apt/lists/*

# Mantener el contenedor corriendo
CMD ["sleep", "infinity"]
